version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - ENV=dev
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - ENV=dev
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8000"
    depends_on:
      - app

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_workflows:/home/node/.n8n/workflows
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_CONFIG_FILES=
      - NODE_ENV=production
      - DB_TYPE=sqlite
      - DB_SQLITE_VACUUM_ON_STARTUP=true
    restart: unless-stopped
    depends_on:
      - app
      - api

volumes:
  n8n_data: