# Data generation configuration

# User profile settings
user_profiles:
  count: 100
  age_range: [18, 85]
  genders: ['male', 'female', 'non-binary']
  sleep_patterns:
    normal: 0.4
    insomnia: 0.25
    shift_worker: 0.15
    oversleeper: 0.1
    variable: 0.1
  device_distribution:
    apple_watch: 0.4
    google_watch: 0.2
    fitbit: 0.3
    samsung_watch: 0.1

# Time settings
time_settings:
  start_date: '2024-01-01'
  end_date: '2024-04-25'
  missing_data_probability: 0.15
  weekend_missing_probability: 0.25

# Sleep pattern parameters
sleep_patterns:
  normal:
    sleep_onset_minutes: [5, 20]
    sleep_duration_hours: [6.5, 8.5]
    awakenings_count: [0, 2]
    awakening_duration_minutes: [1, 10]
    sleep_efficiency: [0.85, 0.95]
    subjective_rating_range: [6, 10]
  
  insomnia:
    sleep_onset_minutes: [30, 120]
    sleep_duration_hours: [4, 6.5]
    awakenings_count: [3, 7]
    awakening_duration_minutes: [10, 60]
    sleep_efficiency: [0.6, 0.8]
    subjective_rating_range: [2, 7]
  
  shift_worker:
    day_sleep_probability: 0.8
    sleep_duration_hours: [5, 7]
    awakenings_count: [2, 5]
    awakening_duration_minutes: [5, 30]
    sleep_efficiency: [0.7, 0.85]
    subjective_rating_range: [4, 8]
  
  oversleeper:
    time_in_bed_hours: [9, 11]
    sleep_duration_hours: [8, 10]
    awakenings_count: [1, 3]
    awakening_duration_minutes: [5, 15]
    sleep_efficiency: [0.75, 0.9]
    subjective_rating_range: [5, 9]
  
  variable:
    bedtime_variance_hours: [1, 3]
    sleep_duration_variance_hours: [1, 3]
    awakening_variance: [0, 5]
    subjective_rating_range: [3, 9]

# Wearable device parameters
device_parameters:
  apple_watch:
    heart_rate_sampling_minutes: 5
    stage_detection_accuracy: 0.85
    movement_sensitivity: 0.9
  
  google_watch:
    heart_rate_sampling_minutes: 10
    stage_detection_accuracy: 0.8
    movement_sensitivity: 0.85
  
  fitbit:
    heart_rate_sampling_minutes: 3
    stage_detection_accuracy: 0.75
    movement_sensitivity: 0.8
  
  samsung_watch:
    heart_rate_sampling_minutes: 7
    stage_detection_accuracy: 0.78
    movement_sensitivity: 0.83